version: '3.7'

services:
  bot:
    build: 
      context: .
      dockerfile: "Dockerfile"
    container_name: "secretary_bot"
    depends_on:
      - mongo
    environment:
      - BOT_MONGO_URI=mongodb://mongo:27017

  mongodb:
    image: mongo:6.0.4
    container_name: "secretary_mongo"
    ports:
      - 27017:27017
    volumes:
      - "./vols/mongo:/data/db"

  mongodb-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017