version: '3.7'

services:
  mongo:
    image: mongo:6.0.4
    container_name: "secretary_mongo"
    ports:
      - 27017:27017
    volumes:
      - "./.vols/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password